### ekf_node config file ###
ekf_filter_node:
    ros__parameters:
        # The frequency, in Hz, at which the filter will output a position estimate. Note that the filter will not begin
        # computation until it receives at least one message from one of the inputs. It will then wait continuously for at
        # least one message to arrive, regardless of the arrival rate.
        frequency: 30.0

        # The period, in seconds, after which we consider a sensor to have timed out. In this event, we carry out a predict
        # cycle on the EKF without correcting it. This parameter can be thought of as the minimum frequency with which the
        # filter will generate new output.
        sensor_timeout: 0.5

        # ekf_localization_node and ukf_localization_node both use a 3D omnidirectional motion model. If this parameter is
        # set to true, no 3D information will be used in your state estimate. Use this if you are operating in a planar
        # environment and want to ignore the effect of small variations in the ground plane that might otherwise be detected
        # by, for example, an IMU. Defaults to false if unspecified.
        two_d_mode: true

        # Use this parameter to provide an offset to the transform generated by ekf_localization_node. This can be used for
        # future dating the transform, which is required for interaction with some other packages. Defaults to 0.0 if
        # unspecified.
        transform_time_offset: 0.0

        # Use this parameter to provide an offset to the transform generated by ekf_localization_node. This can be used for
        # future dating the transform, which is required for interaction with some other packages. Defaults to 0.0 if
        # unspecified.
        transform_timeout: 0.0

        # If you're having trouble, try setting this to true, and then echo the /diagnostics_agg topic to see if the node is
        # unhappy with any settings or data.
        print_diagnostics: true

        # Debug settings. Not for the faint of heart. Outputs a huge amount of information to the file specified by
        # debug_out_file. I hope you like matrices! Please note that setting this to true will have strongly deleterious
        # effects on the performance of the node. Defaults to false if unspecified.
        debug: false

        # Defaults to "map" if unspecified
        map_frame: map
        # Defaults to "odom" if unspecified
        odom_frame: odom
        # Defaults to "base_link" if unspecified
        base_link_frame: base_footprint
        # Defaults to "base_link" if unspecified
        world_frame: odom

        # The filter accepts an arbitrary number of inputs from each input message type (Laserscan, PointCloud2, PoseArray,
        # etc.). To add an input, simply append the next number in the sequence to its "base" name, e.g., odom0, odom1,
        # pose0, pose1, twist0, twist1, imu0, imu1, etc. The value should be the topic name. These parameters obviously have
        # no default values, and must be specified.
        odom0: /odom
        odom0_config: [false, false, false,
                       false, false, false,
                       true,  true,  false,
                       false, false, true,
                       false, false, false]
        odom0_queue_size: 10
        odom0_nodelay: true
        odom0_differential: false
        odom0_relative: false

        imu0: /imu
        imu0_config: [false, false, false,
                      false, false, true,
                      false, false, false,
                      false, false, true,
                      true,  false, false]
        imu0_nodelay: false
        imu0_differential: false
        imu0_relative: true
        imu0_queue_size: 10
        imu0_remove_gravitational_acceleration: true
